package com.heidaner.dingdang.chat;



import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.heidaner.dingdang.R;

/**   
 * @ClassName:  EyeToEyeActivity   
 * @Description:TODO(心犀类)   
 * @author: gjy  
 * @date:   2014421 下午3:38:09   
 *      
 */

public class ChaActivity extends Fragment{

	@Override
	public void onCreate(Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		super.onCreate(savedInstanceState);
		
	}

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		return inflater.inflate(R.layout.activity_chat, container,false);
	}

	
}
