package com.heidaner.dingdang.friend;

import java.util.Collection;

import org.jivesoftware.smack.Roster;
import org.jivesoftware.smack.RosterEntry;

import android.content.Context;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v4.widget.SwipeRefreshLayout.OnRefreshListener;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ListView;

import com.heidaner.dingdang.MainActivity;
import com.heidaner.dingdang.R;
import com.heidaner.dingdang.ddlogin.DDlogin;

/**
 * @ClassName: FriendActivity
 * @Description:TODO(好友类)
 * @author: gjy
 * @date: 201456 下午3:32:10
 * 
 */
public class FriendActivity extends Fragment implements OnRefreshListener {
	private ListView friend_list;
	private View view;
	private SwipeRefreshLayout swipeRefreshLayout;
	private MainActivity ma;
	private Context context;
	@Override
	public void onCreate(Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		super.onCreate(savedInstanceState);
	}

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		// TODO Autogenerated method stub
		view = inflater.inflate(R.layout.activity_friend, container, false);
		initView();
		return view;
	}

	/**
	 * @Title: initView
	 * @Description: TODO(初始化视图)
	 * @param:
	 * @return: void
	 * @throws
	 */
	private void initView() {
		// TODO Autogenerated method stub
		ma=(MainActivity)getActivity();
		context=ma.getApplicationContext();
		swipeRefreshLayout = (SwipeRefreshLayout) view
				.findViewById(R.id.friend_swiperefresh);
		swipeRefreshLayout.setOnRefreshListener(this);
		swipeRefreshLayout.setColorScheme(R.color.blue, R.color.green,
				R.color.black, R.color.red);
		Collection<RosterEntry> rosterEntries=DDlogin.roster.getEntries();
		friend_list = (ListView) view.findViewById(R.id.friend_list);
		friend_list.setAdapter(new FriendListAdapter(context,rosterEntries.toArray()));
	}

	@Override
	public void onRefresh() {
		// TODO Autogenerated method stub

	}

}
